
services:
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: 'true'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka_data:/var/lib/kafka/data
  
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017

  ingestion_service:
    build: ./ingestion_service
    container_name: ingestion_service
    ports:
      - 8000:8000
    environment:
      - KAFKA_URI=kafka:9092
    depends_on:
      - kafka
  
  gridfs_service:
    build: ./gridfs_service
    container_name: gridfs_service
    ports:
      - 8080:8080
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
  
  clean_service:
    build: ./clean_service
    container_name: clean_service
    environment:
      - KAFKA_URI=kafka:9092
    depends_on:
      - kafka
      - ingestion_service

  analytics_service:
    build: ./analytics_service
    container_name: analytics_service
    environment:
      - KAFKA_URI=kafka:9092
    depends_on:
      - kafka
      - clean_service

volumes:
  kafka_data: